sudo: false
language: node_js
node_js:
  - "5.0.0"
  - "4.0.0"
install:
    - npm install --global gulp
    - npm install -g tsd
    - tsd install
    - npm install
after_script:
  - npm run coveralls
git:
  depth: 10
